// This file is generated by Slice Machine. Update with care!

import Etensmenu from './Etensmenu';
import Photogallery from './Photogallery';
import Hero from './Hero';
import Tekstblok from './Tekstblok';

export {
	Etensmenu,
	Photogallery,
	Hero,
	Tekstblok,
};

export const components = {
	menu: Etensmenu,
	foto_galerij: Photogallery,
	hero: Hero,
	pagina_introductie: Tekstblok,
};
