export { default as Text } from './Text'
export { default as Menu } from './Menu'
export { default as Photogallery } from './Photogallery'
export { default as Hero } from './Hero'
export { default as TextWithImage } from './TextWithImage'
export { default as PromoItem } from './Promo'
export { default as Intro } from './Intro'
